targetfile: config/targets.txt
threads: 10
maskfile: workflow/resources/highRepro.sorted.filtered.bed
restriction_analysis_bed: workflow/resources/Twist_ComprehensiveExome_targets_hg38.bed
outputdirectory: results
reference: /n/datg/hg38/hg38.fa
overlapVCF: true
bedRestrict: false
autosomeOnly: true
filterPassing: false
columnNames: shortread,longread